CREATE DATABASE IF NOT EXISTS testDB CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'matsuo'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON testDB.* TO 'matsuo'@'%';

FLUSH PRIVILEGES;